version: '3.4'

services:
  client:
    restart: always
    image: luminodiode/image_indexator_client
    build: 
      context: ./image_indexator_client
      dockerfile: ./dockerfile

  backend:
    restart: always
    image: luminodiode/image_indexator_backend
    build: 
      context: ./image_indexator_backend
      dockerfile: ./dockerfile
    secrets:
      - source: backSecs
        target: secrets.json
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - image_indexator_user_added:wwwroot/user_added

  proxy:
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5050:80"
      

  database:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty_OVERRIDE_ME
      POSTGRES_DB: image_indexator_db_OVERRIDE_ME
    volumes:
      - image_indexator_database:var/lib/postgresql/data

secrets:
  backSecs:
    file: ./backendsecrets.json

  