version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    environment:
      POSTGRES_PASSWORD: iLYA75MUrA
      POSTGRES_DB: image_indexator_db
