version: '3.4'

services:
  client:
    restart: always
    image: luminodiode/image_indexator_client
    build: 
      context: ./image_indexator_client
      dockerfile: ./dockerfile

  backend:
    restart: always
    image: luminodiode/image_indexator_backend
    build: 
      context: ./image_indexator_backend
      dockerfile: ./dockerfile
    secrets:
      - source: backSecs
        target: backendsecrets.json
    environment:
      - ASPNETCORE_URLS=https://+:5002;http://+:5001

  proxy:
    restart: always
    image: nginx
    volumes:
      - ./image_indexator_proxy/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
      

  database:
    restart: always
    image: postgres

secrets:
  backSecs:
    file: ./backendsecrets.json

  