version: '3.4'

services:
  client:
    ports:
      - "5020:3000"

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5002;http://+:5001
    ports:
      - "5011:5001"
      - "5012:5002"

  proxy:
    volumes:
      - ./image_indexator_proxy/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"

  database:
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: image_indexator_db
